/**
 * Express API error handler.
 */

//take error object generated by Express and send JSON response to client used to handle any error that occur in application as a whole

function errorHandler(error, request, response, next) {
  const { status = 500, message = "Something went wrong!" } = error;
  response.status(status).json({ error: message });
}

module.exports = errorHandler;
